import { writeFile } from "node:fs/promises";
import {
  countSetIcons,
  iconSourcesPath,
  metaOutputPath,
  readIconSources,
  writeIconSources,
  type IconSourcesFile,
} from "./icon-sources-shared.ts";

function buildMetaSource(data: IconSourcesFile): string {
  const serialized = JSON.stringify(data.sets, null, 2);

  return `/* eslint-disable */
// Generated by scripts/generate-meta.ts. Do not edit manually.

export type IconSourceUpstream = {
  type: "npm" | "github";
  package: string;
  version: string;
  versionPackage?: string;
  repository: string;
  license: string;
  note?: string;
};

export type IconSourceSet = {
  label: string;
  exportPath: string;
  variants?: string[];
  upstream: IconSourceUpstream;
  syncedAt: string | null;
  iconCount: number;
};

export const iconSources = ${serialized} as const satisfies Record<string, IconSourceSet>;

export type IconSourceName = keyof typeof iconSources;
`;
}

export async function updateIconSourcesCounts(): Promise<IconSourcesFile> {
  const data = await readIconSources();

  for (const [setName, setConfig] of Object.entries(data.sets)) {
    setConfig.iconCount = await countSetIcons(setName, setConfig.variants);
  }

  await writeIconSources(data);
  return data;
}

export async function generateMeta(): Promise<void> {
  const data = await updateIconSourcesCounts();
  await writeFile(metaOutputPath, buildMetaSource(data));
  console.log(`Updated ${iconSourcesPath} and ${metaOutputPath}`);
}

import { pathToFileURL } from "node:url";

const isDirectRun = import.meta.url === pathToFileURL(process.argv[1] ?? "").href;

if (isDirectRun) {
  await generateMeta();
}
