import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(__dirname, "..");
const lucideDir = path.join(packageRoot, "src/animated/lucide");

/** Curated MVP set — exactly 24 icons; order is the public barrel order. */
export const ANIMATED_MVP_COMPONENTS = [
  "ArrowRightAnimatedIcon",
  "ArrowLeftAnimatedIcon",
  "ChevronDownAnimatedIcon",
  "ChevronUpAnimatedIcon",
  "SearchAnimatedIcon",
  "MenuAnimatedIcon",
  "XAnimatedIcon",
  "CheckAnimatedIcon",
  "PlusAnimatedIcon",
  "MinusAnimatedIcon",
  "CopyAnimatedIcon",
  "DownloadAnimatedIcon",
  "UploadAnimatedIcon",
  "RefreshCwAnimatedIcon",
  "SettingsAnimatedIcon",
  "BellAnimatedIcon",
  "Trash2AnimatedIcon",
  "LockAnimatedIcon",
  "LockOpenAnimatedIcon",
  "EyeAnimatedIcon",
  "EyeOffAnimatedIcon",
  "HeartAnimatedIcon",
  "PlayAnimatedIcon",
  "LoaderCircleAnimatedIcon",
] as const;

function componentToSlug(componentName: string): string {
  const base = componentName.replace(/AnimatedIcon$/, "");
  return base
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1-$2")
    .replace(/(\D)(\d+)$/g, "$1-$2")
    .toLowerCase();
}

function componentToIconName(componentName: string): string {
  return componentToSlug(componentName);
}

function componentToRecipeBase(componentName: string): string {
  const slug = componentToSlug(componentName);
  const camel =
    slug.replace(/-([a-z0-9])/g, (_, ch: string) => ch.toUpperCase()).replace(/^./, (c) => c) +
    "Animated";
  return camel.charAt(0).toLowerCase() + camel.slice(1);
}

function parseVariants(recipeSource: string): string[] {
  const match = recipeSource.match(/export type \w+Variant = ([^;]+);/);
  if (!match) {
    return [];
  }
  return match[1]
    .split("|")
    .map((part) => part.trim().replace(/^"|"$/g, ""))
    .filter(Boolean);
}

function parseIntent(recipeSource: string): string {
  const block = recipeSource.match(/intent:\s*\n?\s*"((?:\\.|[^"\\])*)"/s);
  if (block) {
    return block[1];
  }
  const inline = recipeSource.match(/intent:\s*\n?\s*"([^"]+)"/);
  return inline?.[1] ?? "";
}

function parseLoopCapable(recipeSource: string): boolean {
  return /loopCapable:\s*true/.test(recipeSource);
}

function extractParts(tsxSource: string): string[] {
  return [...new Set([...tsxSource.matchAll(/data-kamod-part="([^"]+)"/g)].map((m) => m[1]))];
}

async function loadIconMeta(componentName: string) {
  const slug = componentToSlug(componentName);
  const recipePath = path.join(lucideDir, `${slug}.recipe.ts`);
  const componentPath = path.join(lucideDir, `${componentName}.tsx`);
  const [recipeSource, tsxSource] = await Promise.all([
    readFile(recipePath, "utf8"),
    readFile(componentPath, "utf8"),
  ]);
  const variants = parseVariants(recipeSource);
  const defaultVariant =
    recipeSource.match(/defaultVariant:\s*"([^"]+)"/)?.[1] ?? variants[0] ?? "";
  return {
    componentName,
    iconName: componentToIconName(componentName),
    recipeBase: componentToRecipeBase(componentName),
    slug,
    variants,
    defaultVariant,
    source: "kamod" as const,
    intent: parseIntent(recipeSource),
    loopCapable: parseLoopCapable(recipeSource),
    parts: extractParts(tsxSource),
  };
}

function buildIndexExports(entries: Awaited<ReturnType<typeof loadIconMeta>>[]): string {
  const lines = [
    "/** Generated by scripts/generate-animated-meta.ts — do not edit manually. */",
    'export { AnimateIcon } from "../runtime/animate-icon";',
    "",
  ];

  for (const entry of entries) {
    const variantType = entry.componentName.replace("AnimatedIcon", "AnimatedVariant");
    lines.push(
      `export { ${entry.componentName}, type ${variantType} } from "./${entry.componentName}";`,
    );
  }

  lines.push(
    "",
    "export type {",
    "  AnimatedIconProps,",
    "  AnimateIconProps,",
    "  ReducedMotionMode,",
    "  TriggerTarget,",
    '} from "../runtime/types";',
    "",
  );
  return lines.join("\n");
}

function buildMetaFile(entries: Awaited<ReturnType<typeof loadIconMeta>>[]): string {
  const records = entries.map((entry) => ({
    componentName: entry.componentName,
    iconName: entry.iconName,
    variants: entry.variants,
    defaultVariant: entry.defaultVariant,
    source: entry.source,
    intent: entry.intent,
    loopCapable: entry.loopCapable,
  }));

  return `/** Generated by scripts/generate-animated-meta.ts — do not edit manually. */
export type AnimatedIconMeta = {
  componentName: string;
  iconName: string;
  variants: readonly string[];
  defaultVariant: string;
  source: "kamod";
  intent: string;
  loopCapable: boolean;
};

export const animatedIconMeta = ${JSON.stringify(records, null, 2)} as const satisfies readonly AnimatedIconMeta[];

export const animatedMvpComponentNames = ${JSON.stringify(
    entries.map((e) => e.componentName),
    null,
    2,
  )} as const;
`;
}

function buildCatalogFile(entries: Awaited<ReturnType<typeof loadIconMeta>>[]): string {
  const catalog = entries.map((entry) => ({
    name: entry.componentName,
    componentModule: `./${entry.componentName}`,
    recipeModule: `./${entry.slug}.recipe`,
    recipeExport: `${entry.recipeBase}Recipe`,
    variants: entry.variants,
    ssrMarkers: entry.parts.map((part) => `data-kamod-part="${part}"`),
  }));

  return `/** Generated by scripts/generate-animated-meta.ts — do not edit manually. */
export const animatedLucideCatalog = ${JSON.stringify(catalog, null, 2)} as const;
`;
}

function buildRegistryFile(entries: Awaited<ReturnType<typeof loadIconMeta>>[]): string {
  const imports = entries.flatMap((entry) => [
    `import { ${entry.componentName} } from "./${entry.componentName}";`,
    `import { ${entry.recipeBase}Recipe } from "./${entry.slug}.recipe";`,
  ]);

  const records = entries.map((entry) => {
    return `  {
    name: "${entry.componentName}",
    Icon: ${entry.componentName},
    recipe: ${entry.recipeBase}Recipe,
    variants: [${entry.variants.map((v) => `"${v}"`).join(", ")}],
    ssrMarkers: [${entry.parts.map((p) => `"data-kamod-part=\\"${p}\\""`).join(", ")}],
  }`;
  });

  return `/** Generated by scripts/generate-animated-meta.ts — do not edit manually. */
${imports.join("\n")}

export const animatedLucideTestRegistry = [
${records.join(",\n")},
] as const;
`;
}

async function main() {
  const files = await readdir(lucideDir);
  const discovered = files
    .filter((file) => file.endsWith("AnimatedIcon.tsx"))
    .map((file) => file.replace(/\.tsx$/, ""))
    .sort((a, b) => a.localeCompare(b));

  const missing = ANIMATED_MVP_COMPONENTS.filter((name) => !discovered.includes(name));
  const extra = discovered.filter(
    (name) => !(ANIMATED_MVP_COMPONENTS as readonly string[]).includes(name),
  );

  if (missing.length > 0) {
    throw new Error(`Missing MVP animated components: ${missing.join(", ")}`);
  }
  if (extra.length > 0) {
    throw new Error(`Unexpected animated components outside MVP: ${extra.join(", ")}`);
  }

  const entries = await Promise.all(ANIMATED_MVP_COMPONENTS.map((name) => loadIconMeta(name)));

  await Promise.all([
    writeFile(path.join(lucideDir, "index.ts"), buildIndexExports(entries)),
    writeFile(path.join(lucideDir, "animated-icons.meta.ts"), buildMetaFile(entries)),
    writeFile(path.join(lucideDir, "animated-icons.catalog.ts"), buildCatalogFile(entries)),
    writeFile(path.join(lucideDir, "animated-icons.registry.ts"), buildRegistryFile(entries)),
  ]);

  console.log(`Generated animated barrel + metadata for ${entries.length} MVP icons.`);
}

await main();
