import type { ComponentType } from "preact";
import {
  AlertCircleIcon as ShadcnAlertCircleIcon,
  BellIcon as ShadcnBellIcon,
  CalendarIcon as ShadcnCalendarIcon,
  CheckIcon as ShadcnCheckIcon,
  HomeIcon as ShadcnHomeIcon,
  MenuIcon as ShadcnMenuIcon,
  SearchIcon as ShadcnSearchIcon,
  SettingsIcon as ShadcnSettingsIcon,
  StarIcon as ShadcnStarIcon,
  UserIcon as ShadcnUserIcon,
  XIcon as ShadcnXIcon,
  ZapIcon as ShadcnZapIcon,
} from "@kamod-ch/icons/shadcn";
import {
  BadgeAlertIcon as LucideBadgeAlertIcon,
  BellIcon as LucideBellIcon,
  CalendarIcon as LucideCalendarIcon,
  CheckIcon as LucideCheckIcon,
  HouseIcon as LucideHouseIcon,
  MenuIcon as LucideMenuIcon,
  SearchIcon as LucideSearchIcon,
  SettingsIcon as LucideSettingsIcon,
  StarIcon as LucideStarIcon,
  UserIcon as LucideUserIcon,
  XIcon as LucideXIcon,
  ZapIcon as LucideZapIcon,
} from "@kamod-ch/icons/lucide";
import {
  BellIcon as HeroBellIcon,
  CalendarIcon as HeroCalendarIcon,
  CheckIcon as HeroCheckIcon,
  ExclamationCircleIcon as HeroExclamationCircleIcon,
  HomeIcon as HeroHomeIcon,
  MagnifyingGlassIcon as HeroMagnifyingGlassIcon,
  StarIcon as HeroStarIcon,
  UserIcon as HeroUserIcon,
  XMarkIcon as HeroXMarkIcon,
  Cog6ToothIcon as HeroCog6ToothIcon,
  Bars3Icon as HeroBars3Icon,
  BoltIcon as HeroBoltIcon,
} from "@kamod-ch/icons/heroicons/outline";
import {
  AlertCircleIcon as TablerAlertCircleIcon,
  BellIcon as TablerBellIcon,
  CalendarIcon as TablerCalendarIcon,
  CheckIcon as TablerCheckIcon,
  HomeIcon as TablerHomeIcon,
  MenuIcon as TablerMenuIcon,
  SearchIcon as TablerSearchIcon,
  SettingsIcon as TablerSettingsIcon,
  StarIcon as TablerStarIcon,
  UserIcon as TablerUserIcon,
  XIcon as TablerXIcon,
  BoltIcon as TablerBoltIcon,
} from "@kamod-ch/icons/tabler/outline";
import {
  BellIcon as IconoirBellIcon,
  CalendarIcon as IconoirCalendarIcon,
  CheckIcon as IconoirCheckIcon,
  HomeIcon as IconoirHomeIcon,
  MenuIcon as IconoirMenuIcon,
  SearchIcon as IconoirSearchIcon,
  SettingsIcon as IconoirSettingsIcon,
  StarIcon as IconoirStarIcon,
  UserIcon as IconoirUserIcon,
  WarningCircleIcon as IconoirWarningCircleIcon,
  XIcon as IconoirXIcon,
  FlashIcon as IconoirFlashIcon,
} from "@kamod-ch/icons/iconoir/regular";
import {
  AlertCircleIcon as ReiconAlertCircleIcon,
  BellIcon as ReiconBellIcon,
  BoltIcon as ReiconBoltIcon,
  CalendarIcon as ReiconCalendarIcon,
  CheckIcon as ReiconCheckIcon,
  CloseCircle2Icon as ReiconCloseCircle2Icon,
  HomeIcon as ReiconHomeIcon,
  MenuIcon as ReiconMenuIcon,
  SearchIcon as ReiconSearchIcon,
  SettingsIcon as ReiconSettingsIcon,
  Star2Icon as ReiconStar2Icon,
  UserIcon as ReiconUserIcon,
} from "@kamod-ch/icons/reicon/outline";
import { iconSources, type IconSourceName } from "@kamod-ch/icons/meta";

export type IconComponent = ComponentType<{ size?: number; class?: string; "aria-hidden"?: string | boolean }>;
export type IconItem = [name: string, Icon: IconComponent];
export type IconSet = {
  id: IconSourceName;
  label: string;
  importPath: string;
  description: string;
  iconCount: number;
  icons: IconItem[];
};

export const iconSets: IconSet[] = [
  {
    id: "shadcn",
    label: "shadcn",
    importPath: "@kamod-ch/icons/shadcn",
    description: "Balanced UI icons with a crisp app-ready style.",
    iconCount: iconSources.shadcn.iconCount,
    icons: [
      ["Search", ShadcnSearchIcon],
      ["Check", ShadcnCheckIcon],
      ["AlertCircle", ShadcnAlertCircleIcon],
      ["Settings", ShadcnSettingsIcon],
      ["User", ShadcnUserIcon],
      ["Menu", ShadcnMenuIcon],
      ["X", ShadcnXIcon],
      ["Calendar", ShadcnCalendarIcon],
      ["Bell", ShadcnBellIcon],
      ["Home", ShadcnHomeIcon],
      ["Star", ShadcnStarIcon],
      ["Zap", ShadcnZapIcon],
    ],
  },
  {
    id: "lucide",
    label: "Lucide",
    importPath: "@kamod-ch/icons/lucide",
    description: "Clean, lightweight line icons for modern product interfaces.",
    iconCount: iconSources.lucide.iconCount,
    icons: [
      ["Search", LucideSearchIcon],
      ["Check", LucideCheckIcon],
      ["BadgeAlert", LucideBadgeAlertIcon],
      ["Settings", LucideSettingsIcon],
      ["User", LucideUserIcon],
      ["Menu", LucideMenuIcon],
      ["X", LucideXIcon],
      ["Calendar", LucideCalendarIcon],
      ["Bell", LucideBellIcon],
      ["House", LucideHouseIcon],
      ["Star", LucideStarIcon],
      ["Zap", LucideZapIcon],
    ],
  },
  {
    id: "heroicons",
    label: "Heroicons",
    importPath: "@kamod-ch/icons/heroicons/outline",
    description: "Friendly outline icons that work well in dashboards and docs.",
    iconCount: iconSources.heroicons.iconCount,
    icons: [
      ["MagnifyingGlass", HeroMagnifyingGlassIcon],
      ["Check", HeroCheckIcon],
      ["ExclamationCircle", HeroExclamationCircleIcon],
      ["Cog6Tooth", HeroCog6ToothIcon],
      ["User", HeroUserIcon],
      ["Bars3", HeroBars3Icon],
      ["XMark", HeroXMarkIcon],
      ["Calendar", HeroCalendarIcon],
      ["Bell", HeroBellIcon],
      ["Home", HeroHomeIcon],
      ["Star", HeroStarIcon],
      ["Bolt", HeroBoltIcon],
    ],
  },
  {
    id: "tabler",
    label: "Tabler",
    importPath: "@kamod-ch/icons/tabler/outline",
    description: "A broad, practical set for product screens, tools, and admin UIs.",
    iconCount: iconSources.tabler.iconCount,
    icons: [
      ["Search", TablerSearchIcon],
      ["Check", TablerCheckIcon],
      ["AlertCircle", TablerAlertCircleIcon],
      ["Settings", TablerSettingsIcon],
      ["User", TablerUserIcon],
      ["Menu", TablerMenuIcon],
      ["X", TablerXIcon],
      ["Calendar", TablerCalendarIcon],
      ["Bell", TablerBellIcon],
      ["Home", TablerHomeIcon],
      ["Star", TablerStarIcon],
      ["Bolt", TablerBoltIcon],
    ],
  },
  {
    id: "iconoir",
    label: "Iconoir",
    importPath: "@kamod-ch/icons/iconoir/regular",
    description: "Distinctive geometric icons for expressive product moments.",
    iconCount: iconSources.iconoir.iconCount,
    icons: [
      ["Search", IconoirSearchIcon],
      ["Check", IconoirCheckIcon],
      ["WarningCircle", IconoirWarningCircleIcon],
      ["Settings", IconoirSettingsIcon],
      ["User", IconoirUserIcon],
      ["Menu", IconoirMenuIcon],
      ["X", IconoirXIcon],
      ["Calendar", IconoirCalendarIcon],
      ["Bell", IconoirBellIcon],
      ["Home", IconoirHomeIcon],
      ["Star", IconoirStarIcon],
      ["Flash", IconoirFlashIcon],
    ],
  },
  {
    id: "reicon",
    label: "Reicon",
    importPath: "@kamod-ch/icons/reicon/outline",
    description: "Large open-source icon library with outline and filled weights.",
    iconCount: iconSources.reicon.iconCount,
    icons: [
      ["Search", ReiconSearchIcon],
      ["Check", ReiconCheckIcon],
      ["AlertCircle", ReiconAlertCircleIcon],
      ["Settings", ReiconSettingsIcon],
      ["User", ReiconUserIcon],
      ["Menu", ReiconMenuIcon],
      ["CloseCircle2", ReiconCloseCircle2Icon],
      ["Calendar", ReiconCalendarIcon],
      ["Bell", ReiconBellIcon],
      ["Home", ReiconHomeIcon],
      ["Star2", ReiconStar2Icon],
      ["Bolt", ReiconBoltIcon],
    ],
  },
];
