/** Generated by scripts/generate-animated-meta.ts — do not edit manually. */
import { ArrowRightAnimatedIcon } from "./ArrowRightAnimatedIcon";
import { arrowRightAnimatedRecipe } from "./arrow-right.recipe";
import { ArrowLeftAnimatedIcon } from "./ArrowLeftAnimatedIcon";
import { arrowLeftAnimatedRecipe } from "./arrow-left.recipe";
import { ChevronDownAnimatedIcon } from "./ChevronDownAnimatedIcon";
import { chevronDownAnimatedRecipe } from "./chevron-down.recipe";
import { ChevronUpAnimatedIcon } from "./ChevronUpAnimatedIcon";
import { chevronUpAnimatedRecipe } from "./chevron-up.recipe";
import { SearchAnimatedIcon } from "./SearchAnimatedIcon";
import { searchAnimatedRecipe } from "./search.recipe";
import { MenuAnimatedIcon } from "./MenuAnimatedIcon";
import { menuAnimatedRecipe } from "./menu.recipe";
import { XAnimatedIcon } from "./XAnimatedIcon";
import { xAnimatedRecipe } from "./x.recipe";
import { CheckAnimatedIcon } from "./CheckAnimatedIcon";
import { checkAnimatedRecipe } from "./check.recipe";
import { PlusAnimatedIcon } from "./PlusAnimatedIcon";
import { plusAnimatedRecipe } from "./plus.recipe";
import { MinusAnimatedIcon } from "./MinusAnimatedIcon";
import { minusAnimatedRecipe } from "./minus.recipe";
import { CopyAnimatedIcon } from "./CopyAnimatedIcon";
import { copyAnimatedRecipe } from "./copy.recipe";
import { DownloadAnimatedIcon } from "./DownloadAnimatedIcon";
import { downloadAnimatedRecipe } from "./download.recipe";
import { UploadAnimatedIcon } from "./UploadAnimatedIcon";
import { uploadAnimatedRecipe } from "./upload.recipe";
import { RefreshCwAnimatedIcon } from "./RefreshCwAnimatedIcon";
import { refreshCwAnimatedRecipe } from "./refresh-cw.recipe";
import { SettingsAnimatedIcon } from "./SettingsAnimatedIcon";
import { settingsAnimatedRecipe } from "./settings.recipe";
import { BellAnimatedIcon } from "./BellAnimatedIcon";
import { bellAnimatedRecipe } from "./bell.recipe";
import { Trash2AnimatedIcon } from "./Trash2AnimatedIcon";
import { trash2AnimatedRecipe } from "./trash-2.recipe";
import { LockAnimatedIcon } from "./LockAnimatedIcon";
import { lockAnimatedRecipe } from "./lock.recipe";
import { LockOpenAnimatedIcon } from "./LockOpenAnimatedIcon";
import { lockOpenAnimatedRecipe } from "./lock-open.recipe";
import { EyeAnimatedIcon } from "./EyeAnimatedIcon";
import { eyeAnimatedRecipe } from "./eye.recipe";
import { EyeOffAnimatedIcon } from "./EyeOffAnimatedIcon";
import { eyeOffAnimatedRecipe } from "./eye-off.recipe";
import { HeartAnimatedIcon } from "./HeartAnimatedIcon";
import { heartAnimatedRecipe } from "./heart.recipe";
import { PlayAnimatedIcon } from "./PlayAnimatedIcon";
import { playAnimatedRecipe } from "./play.recipe";
import { LoaderCircleAnimatedIcon } from "./LoaderCircleAnimatedIcon";
import { loaderCircleAnimatedRecipe } from "./loader-circle.recipe";

export const animatedLucideTestRegistry = [
  {
    name: "ArrowRightAnimatedIcon",
    Icon: ArrowRightAnimatedIcon,
    recipe: arrowRightAnimatedRecipe,
    variants: ["advance"],
    ssrMarkers: ['data-kamod-part="arrow"'],
  },
  {
    name: "ArrowLeftAnimatedIcon",
    Icon: ArrowLeftAnimatedIcon,
    recipe: arrowLeftAnimatedRecipe,
    variants: ["retreat"],
    ssrMarkers: ['data-kamod-part="arrow"'],
  },
  {
    name: "ChevronDownAnimatedIcon",
    Icon: ChevronDownAnimatedIcon,
    recipe: chevronDownAnimatedRecipe,
    variants: ["expand"],
    ssrMarkers: ['data-kamod-part="chevron"'],
  },
  {
    name: "ChevronUpAnimatedIcon",
    Icon: ChevronUpAnimatedIcon,
    recipe: chevronUpAnimatedRecipe,
    variants: ["collapse"],
    ssrMarkers: ['data-kamod-part="chevron"'],
  },
  {
    name: "SearchAnimatedIcon",
    Icon: SearchAnimatedIcon,
    recipe: searchAnimatedRecipe,
    variants: ["scan"],
    ssrMarkers: ['data-kamod-part="lens"', 'data-kamod-part="handle"'],
  },
  {
    name: "MenuAnimatedIcon",
    Icon: MenuAnimatedIcon,
    recipe: menuAnimatedRecipe,
    variants: ["spread"],
    ssrMarkers: [
      'data-kamod-part="line-top"',
      'data-kamod-part="line-mid"',
      'data-kamod-part="line-bottom"',
    ],
  },
  {
    name: "XAnimatedIcon",
    Icon: XAnimatedIcon,
    recipe: xAnimatedRecipe,
    variants: ["dismiss"],
    ssrMarkers: ['data-kamod-part="stroke-a"', 'data-kamod-part="stroke-b"'],
  },
  {
    name: "CheckAnimatedIcon",
    Icon: CheckAnimatedIcon,
    recipe: checkAnimatedRecipe,
    variants: ["draw"],
    ssrMarkers: ['data-kamod-part="mark"'],
  },
  {
    name: "PlusAnimatedIcon",
    Icon: PlusAnimatedIcon,
    recipe: plusAnimatedRecipe,
    variants: ["add"],
    ssrMarkers: ['data-kamod-part="bar-h"', 'data-kamod-part="bar-v"'],
  },
  {
    name: "MinusAnimatedIcon",
    Icon: MinusAnimatedIcon,
    recipe: minusAnimatedRecipe,
    variants: ["remove"],
    ssrMarkers: ['data-kamod-part="bar"'],
  },
  {
    name: "CopyAnimatedIcon",
    Icon: CopyAnimatedIcon,
    recipe: copyAnimatedRecipe,
    variants: ["duplicate"],
    ssrMarkers: ['data-kamod-part="front"', 'data-kamod-part="back"'],
  },
  {
    name: "DownloadAnimatedIcon",
    Icon: DownloadAnimatedIcon,
    recipe: downloadAnimatedRecipe,
    variants: ["fetch"],
    ssrMarkers: ['data-kamod-part="arrow"', 'data-kamod-part="tray"'],
  },
  {
    name: "UploadAnimatedIcon",
    Icon: UploadAnimatedIcon,
    recipe: uploadAnimatedRecipe,
    variants: ["send"],
    ssrMarkers: ['data-kamod-part="arrow"', 'data-kamod-part="tray"'],
  },
  {
    name: "RefreshCwAnimatedIcon",
    Icon: RefreshCwAnimatedIcon,
    recipe: refreshCwAnimatedRecipe,
    variants: ["spin"],
    ssrMarkers: ['data-kamod-part="glyph"'],
  },
  {
    name: "SettingsAnimatedIcon",
    Icon: SettingsAnimatedIcon,
    recipe: settingsAnimatedRecipe,
    variants: ["adjust", "spin"],
    ssrMarkers: ['data-kamod-part="gear"', 'data-kamod-part="hub"'],
  },
  {
    name: "BellAnimatedIcon",
    Icon: BellAnimatedIcon,
    recipe: bellAnimatedRecipe,
    variants: ["ring"],
    ssrMarkers: ['data-kamod-part="body"', 'data-kamod-part="clapper"'],
  },
  {
    name: "Trash2AnimatedIcon",
    Icon: Trash2AnimatedIcon,
    recipe: trash2AnimatedRecipe,
    variants: ["delete"],
    ssrMarkers: ['data-kamod-part="lid"', 'data-kamod-part="bin"'],
  },
  {
    name: "LockAnimatedIcon",
    Icon: LockAnimatedIcon,
    recipe: lockAnimatedRecipe,
    variants: ["secure"],
    ssrMarkers: ['data-kamod-part="body"', 'data-kamod-part="shackle"'],
  },
  {
    name: "LockOpenAnimatedIcon",
    Icon: LockOpenAnimatedIcon,
    recipe: lockOpenAnimatedRecipe,
    variants: ["unlock"],
    ssrMarkers: ['data-kamod-part="body"', 'data-kamod-part="shackle"'],
  },
  {
    name: "EyeAnimatedIcon",
    Icon: EyeAnimatedIcon,
    recipe: eyeAnimatedRecipe,
    variants: ["look", "blink"],
    ssrMarkers: ['data-kamod-part="outline"', 'data-kamod-part="pupil"'],
  },
  {
    name: "EyeOffAnimatedIcon",
    Icon: EyeOffAnimatedIcon,
    recipe: eyeOffAnimatedRecipe,
    variants: ["conceal"],
    ssrMarkers: ['data-kamod-part="eye"', 'data-kamod-part="strike"'],
  },
  {
    name: "HeartAnimatedIcon",
    Icon: HeartAnimatedIcon,
    recipe: heartAnimatedRecipe,
    variants: ["pulse", "selected"],
    ssrMarkers: ['data-kamod-part="heart"'],
  },
  {
    name: "PlayAnimatedIcon",
    Icon: PlayAnimatedIcon,
    recipe: playAnimatedRecipe,
    variants: ["play"],
    ssrMarkers: ['data-kamod-part="triangle"'],
  },
  {
    name: "LoaderCircleAnimatedIcon",
    Icon: LoaderCircleAnimatedIcon,
    recipe: loaderCircleAnimatedRecipe,
    variants: ["spin"],
    ssrMarkers: ['data-kamod-part="arc"'],
  },
] as const;
